name: flutter_fb_news
description: Flutter plugin for displaying Facebook page feed with photos and videos
version: 2.0.0
homepage: https://github.com/cedteg/flutter_fb_news
repository: https://github.com/cedteg/flutter_fb_news
issue_tracker: https://github.com/cedteg/flutter_fb_news/issues

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.6"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.0.0
  chewie: ^1.0.0
  flutter_linkify: ^5.0.0
  http: ^0.13.1
  url_launcher: ^6.0.3
  video_player: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
