name: flutter_fb_news
description: Flutter plugin for displaying Facebook page feed with photos and videos
version: 0.0.5
homepage: https://github.com/cedteg/flutter_fb_news

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.12.2
  carousel_slider: ^2.3.1
  url_launcher: ^5.7.10
  chewie: ^0.12.1+1
  video_player: ^1.0.1
  meta: ^1.2.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: