name: flutter_fb_news
description: A new Flutter package.
version: 0.0.1
author: cedteg <cedtegapps.de@gmail.com>
homepage: https://github.com/cedteg/flutter_fb_news

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.12.2
  carousel_slider: ^2.3.1
  url_launcher: ^5.7.10
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: