name: flutter_fb_news
description: Flutter plugin for displaying Facebook page feed with photos and videos
version: 1.1.2+1
homepage: https://github.com/cedteg/flutter_fb_news
repository: https://github.com/cedteg/flutter_fb_news
issue_tracker: https://github.com/cedteg/flutter_fb_news/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.5"

dependencies:
  http: ^0.12.2
  carousel_slider: ^2.3.3
  url_launcher: ^5.7.10
  chewie: ^0.12.2
  video_player: ^1.0.1
  flutter_linkify: ^3.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  import_sorter: ^4.4.1

flutter: